# Generated by Django 4.1.7 on 2023-06-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_popupimage_product_discount_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('text', models.TextField()),
                ('video', models.URLField(blank=True)),
                ('link', models.URLField(blank=True)),
            ],
        ),
    ]
